services:
  sample:
    build: example/app
    image: sample:latest
    env_file: .env
    depends_on:
      - postgres
      - mongodb
    ports:
      - "8080:8080"

  postgres:
    image: postgres:12.4-alpine
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./example/scripts/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh

  mongodb:
    image: mongo:4.4-bionic
    env_file: .env
    ports:
      - "27017:27017"
    volumes:
      - ./example/scripts/mongodb/init.sh:/docker-entrypoint-initdb.d/init.sh
