comments:
  AbsentOrWrongFileLicense:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - ArrayIndexOutOfBoundsException
      - Error
      - IllegalMonitorStateException
      - NullPointerException
      - IndexOutOfBoundsException
      - RuntimeException
      - Throwable
    allowedExceptionNameRegex: '^(_|(ignore|expected).*)'

formatting:
  Indentation:
    active: true
    autoCorrect: true
    indentSize: 2
    continuationIndentSize: 2
  ParameterListWrapping:
    active: true
    autoCorrect: true
    indentSize: 2
