name: Run smoke build with checks & test

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build example app
        run: ./gradlew :app:build
